CREATE OR REPLACE EXTERNAL TABLE `netflix-pipeline-491410.bronze_data.raw_belief_data` 
(
  userId STRING OPTIONS(description="Unique identifier for the user participating in the belief study."),
  movieId STRING OPTIONS(description="Unique identifier for the movie being evaluated."),
  isSeen STRING OPTIONS(description="Categorical flag for view status: 1 (Seen), 0 (Not Seen), -1 (Unknown/No data)."),
  watchDate STRING OPTIONS(description="The specific date the user watched the movie (often null if isSeen is -1)."),
  userElicitRating STRING OPTIONS(description="The rating explicitly asked from the user during the interaction (-1 if not provided)."),
  userPredictRating STRING OPTIONS(description="The user's own prediction of how much they would like the movie."),
  userCertainty STRING OPTIONS(description="A confidence score provided by the user regarding their own rating prediction."),
  tstamp STRING OPTIONS(description="The wall-clock timestamp when this specific interaction/row was logged."),
  movie_idx STRING OPTIONS(description="The positional index or sequence number of the movie in the recommendation list."),
  source STRING OPTIONS(description="The origin of the recommendation (e.g., algorithm version 1 vs version 2)."),
  systemPredictRating STRING OPTIONS(description="The raw floating-point score generated by the ML model (e.g., 4.447).")
)
OPTIONS (
  format = 'CSV',
  uris = ['gs://netflix-data-pipeline/bronze/belief_data.csv'],
  skip_leading_rows = 1,
  allow_quoted_newlines = TRUE,
  allow_jagged_rows = TRUE
);
