#!/bin/bash

source .env

echo "Generating JSON structure for external tables..."

cat > /tmp/ext_belief_data.json <<EOF
{ 
  "sourceFormat": "CSV",
  "sourceUris": ["gs://${BUCKET_NAME}/${FOLDER_NAME}/belief_data.csv"],
  "csvOptions": {
    "skipLeadingRows": 1,
    "allowQuotedNewlines": true
  },
  "schema": {
    "fields": [
      { "name": "userId",              "type": "STRING", "description": "Unique identifier for the user participating in the belief study." },
      { "name": "movieId",             "type": "STRING", "description": "Unique identifier for the movie being evaluated." },
      { "name": "isSeen",              "type": "STRING", "description": "Categorical flag for view status: 1 (Seen), 0 (Not Seen), -1 (Unknown/No data)." },
      { "name": "watchDate",           "type": "STRING", "description": "The specific date the user watched the movie (often null if isSeen is -1)." },
      { "name": "userElicitRating",    "type": "STRING", "description": "The rating explicitly asked from the user during the interaction (-1 if not provided)." },
      { "name": "userPredictRating",   "type": "STRING", "description": "The user's own prediction of how much they would like the movie." },
      { "name": "userCertainty",       "type": "STRING", "description": "A confidence score provided by the user regarding their own rating prediction." },
      { "name": "tstamp",              "type": "STRING", "description": "The wall-clock timestamp when this specific interaction/row was logged." },      
      { "name": "movie_idx",           "type": "STRING", "description": "The positional index or sequence number of the movie in the recommendation list." },
      { "name": "source",              "type": "STRING", "description": "The origin of the recommendation (e.g., algorithm version 1 vs version 2)." },
      { "name": "systemPredictRating", "type": "STRING", "description": "The raw floating-point score generated by the ML model (e.g., 4.447)." }
    ]
  }
}
EOF

cat > /tmp/ext_movie_elicitation_set.json <<EOF
{
  "sourceFormat": "CSV",
  "sourceUris": ["gs://${BUCKET_NAME}/${FOLDER_NAME}/movie_elicitation_set.csv"],
  "csvOptions": {
    "skipLeadingRows": 1
  },
  "schema": {
    "fields": [
      { "name": "movieId",   "type": "STRING", "description": "Unique identifier for the movie being presented for elicitation." },
      { "name": "month_idx", "type": "STRING", "description": "The relative month number in the study (e.g., 0 = January, 1 = February)." },
      { "name": "source",    "type": "STRING", "description": "The experimental group or algorithm version responsible for this elicitation." },
      { "name": "tstamp",    "type": "STRING", "description": "The precise timestamp marking the start of the elicitation window for this movie." }
    ]
  }
}
EOF

cat > /tmp/ext_movies.json <<EOF
{
  "sourceFormat": "CSV",
  "sourceUris": ["gs://${BUCKET_NAME}/${FOLDER_NAME}/movies.csv"],
  "csvOptions": {
    "skipLeadingRows": 1
  },
  "schema": {
    "fields": [
      { "name": "movieId", "type": "STRING", "description": "Unique identifier for the movie." },
      { "name": "title",   "type": "STRING", "description": "The full display title of the movie, often including the release year." },
      { "name": "genres",  "type": "STRING", "description": "Pipe-separated list of movie categories (e.g., Adventure|Children|Fantasy)." }
    ]
  }
}
EOF

cat > /tmp/ext_ratings_for_additional_users.json <<EOF
{
  "sourceFormat": "CSV",
  "sourceUris": ["gs://${BUCKET_NAME}/${FOLDER_NAME}/ratings_for_additional_users.csv"],
  "csvOptions": {
    "skipLeadingRows": 1
  },
  "schema": {
    "fields": [
      { "name": "userId",  "type": "STRING", "description": "Unique identifier for the supplementary user providing the rating." },
      { "name": "movieId", "type": "STRING", "description": "Unique identifier for the movie being rated." },
      { "name": "rating",  "type": "STRING", "description": "The actual score given by the user (typically on a scale of 0.5 - 5.0)." },
      { "name": "tstamp",  "type": "STRING", "description": "The timestamp when the rating was recorded." }
    ]
  }
}
EOF

cat > /tmp/ext_user_rating_history.json <<EOF
{
  "sourceFormat": "CSV",
  "sourceUris": ["gs://${BUCKET_NAME}/${FOLDER_NAME}/user_rating_history.csv"],
  "csvOptions": {
    "skipLeadingRows": 1
  },
  "schema": {
    "fields": [
      { "name": "userId",  "type": "STRING", "description": "Unique identifier for the user who provided the rating." },
      { "name": "movieId", "type": "STRING", "description": "Unique identifier for the movie being rated." },
      { "name": "rating",  "type": "STRING", "description": "The numerical score assigned to the movie (e.g., 1-5 stars)." },
      { "name": "tstamp",  "type": "STRING", "description": "The date and time when the rating was recorded." }
    ]
  }
}
EOF

cat > /tmp/ext_user_recommendation_history.json <<EOF
{
  "sourceFormat": "CSV",
  "sourceUris": ["gs://${BUCKET_NAME}/${FOLDER_NAME}/user_recommendation_history.csv"],
  "csvOptions": {
    "skipLeadingRows": 1
  },
  "schema": {
    "fields": [
      { "name": "userId",          "type": "STRING", "description": "Unique identifier for the user to whom the recommendation was made." },
      { "name": "tstamp",          "type": "STRING", "description": "The timestamp when the recommendation was generated or recorded." },
      { "name": "movieId",         "type": "STRING", "description": "Unique identifier for the recommended movie." },
      { "name": "predictedRating", "type": "STRING", "description": "The model-generated score predicting user preference (e.g., 1.0 - 5.0)." }
    ]
  }
}
EOF

echo "Generating external tables on layer: $BRONZE_DATASET"

bq mk \
  --force \
  --external_table_definition=/tmp/ext_belief_data.json \
  ${BRONZE_DATASET}.raw_belief_data

bq mk \
  --force \
  --external_table_definition=/tmp/ext_movie_elicitation_set.json \
  ${BRONZE_DATASET}.raw_movie_elicitation_set

bq mk \
  --force \
  --external_table_definition=/tmp/ext_movies.json \
  ${BRONZE_DATASET}.raw_movies

bq mk \
  --force \
  --external_table_definition=/tmp/ext_ratings_for_additional_users.json \
  ${BRONZE_DATASET}.raw_ratings_for_additional_users

bq mk \
  --force \
  --external_table_definition=/tmp/ext_user_rating_history.json \
  ${BRONZE_DATASET}.raw_user_rating_history

bq mk \
  --force \
  --external_table_definition=/tmp/ext_user_recommendation_history.json \
  ${BRONZE_DATASET}.raw_user_recommendation_history   

echo "Bronze tables successfully generated!"
